package com.example.api.enums;

public enum TicketStatus {
    OPEN,
    ASSIGNED,
    PENDING,
    CLOSED,
    ON_HOLD,
    REOPENED,
    RESOLVED,
    ASSIGN_FURTHER,
    CANCELLED,
    PENDING_WITH_REQUESTER,
    PENDING_WITH_SERVICE_PROVIDER,
    PENDING_WITH_FCI,
    AWAITING_ESCALATION_APPROVAL,
    ESCALATED
}
