import React from "react";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useSnackbar } from "../context/SnackbarContext";
import { getCurrentUserDetails } from "../config/config";
import {
    calculateColumnWidths,
    applyThinBorders,
    extractApiPayload,
    formatDateInput,
} from "../utils/misReports";
import {
    fetchCustomerSatisfactionReport,
    fetchProblemManagementReport,
    fetchTicketResolutionTimeReport,
    fetchTicketSummaryReport,
} from "../services/ReportService";
import {
    CustomerSatisfactionReportProps,
    MISReportRequestParams,
    ProblemManagementReportProps,
    ReportPeriod,
    ReportRange,
    TicketResolutionTimeReportProps,
    TicketSummaryReportProps,
} from "../types/reports";
import { getPeriodLabel } from "../utils/reportPeriods";

export interface UseMisReportDownloaderResult {
    downloading: boolean;
    handleDownload: (option: string, period: ReportPeriod, range: ReportRange) => Promise<void>;
    handleEmail: (period: ReportPeriod, range: ReportRange) => void;
}

export const useMisReportDownloader = (
    requestParams: MISReportRequestParams,
): UseMisReportDownloaderResult => {
    const { showMessage } = useSnackbar();
    const userDetails = React.useMemo(() => getCurrentUserDetails(), []);
    const [downloading, setDownloading] = React.useState(false);

    const loadReports = React.useCallback(async () => {
        const [ticketSummaryResponse, resolutionResponse, satisfactionResponse, problemResponse] = await Promise.all([
            fetchTicketSummaryReport(requestParams),
            fetchTicketResolutionTimeReport(requestParams),
            fetchCustomerSatisfactionReport(requestParams),
            fetchProblemManagementReport(requestParams),
        ]);

        const ticketSummary = extractApiPayload<TicketSummaryReportProps>(ticketSummaryResponse);
        const resolutionTime = extractApiPayload<TicketResolutionTimeReportProps>(resolutionResponse);
        const satisfaction = extractApiPayload<CustomerSatisfactionReportProps>(satisfactionResponse);
        const problemManagement = extractApiPayload<ProblemManagementReportProps>(problemResponse);

        if (!ticketSummary || !resolutionTime || !satisfaction || !problemManagement) {
            throw new Error("Incomplete data received for MIS reports.");
        }

        return { ticketSummary, resolutionTime, satisfaction, problemManagement };
    }, [requestParams]);

    const buildMetadataRows = React.useCallback((title: string, range: ReportRange) => {
        const downloadedBy = userDetails?.username || userDetails?.userId || "Unknown User";
        const downloadedOn = new Date();
        const fromDateLabel = requestParams.fromDate || formatDateInput(range.startDate);
        const toDateLabel = requestParams.toDate || formatDateInput(range.endDate);

        const formatDisplayDate = (value: string | Date) =>
            new Date(value).toLocaleDateString(undefined, {
                year: "numeric",
                month: "short",
                day: "numeric",
            });

        const filterRows = Object.entries(requestParams)
            .filter(([, value]) => value !== undefined && value !== null && value !== "")
            .map(([key, value]) => [key, String(value)] as (string | number)[]);

        return [
            [title],
            ["Report Generated By", downloadedBy],
            ["Generated On", downloadedOn.toLocaleString()],
            ["Date Range From", formatDisplayDate(fromDateLabel)],
            ["Date Range To", formatDisplayDate(toDateLabel)],
            ["Applied Filters", ""],
            ...filterRows,
            [],
        ];
    }, [requestParams, userDetails?.userId, userDetails?.username]);

    const downloadExcel = React.useCallback(async (period: ReportPeriod, range: ReportRange) => {
        setDownloading(true);

        try {
            const { ticketSummary, resolutionTime, satisfaction, problemManagement } = await loadReports();

            const workbook = XLSX.utils.book_new();

            const summaryRows: (string | number)[][] = [
                ...buildMetadataRows("Ticket Summary Report", range),
                ["Ticket Summary"],
                ["Total Tickets", "Open Tickets", "Closed Tickets"],
                [ticketSummary.totalTickets, ticketSummary.openTickets, ticketSummary.closedTickets],
                [],
                ["Status", "Count"],
                ...Object.entries(ticketSummary.statusCounts ?? {}).map(([status, count]) => [status, count]),
                [],
                ["Mode", "Count"],
                ...Object.entries(ticketSummary.modeCounts ?? {}).map(([mode, count]) => [mode, count]),
            ];

            const resolutionRows: (string | number)[][] = [
                ...buildMetadataRows("Ticket Resolution Time Report", range),
                ["Ticket Resolution Time"],
                ["Average Resolution Hours", "Tickets Considered"],
                [Number(resolutionTime.averageResolutionHours?.toFixed?.(2) ?? resolutionTime.averageResolutionHours ?? 0), resolutionTime.resolvedTicketCount ?? 0],
                [],
                ["Category", "Sub Category", "Average Resolution (hrs)", "Resolved Tickets", "Closed Tickets"],
                ...(resolutionTime.categoryStats?.length
                    ? resolutionTime.categoryStats.map((entry) => [
                        entry.categoryName ?? entry.category ?? "N/A",
                        entry.subcategoryName ?? entry.subcategory ?? "N/A",
                        Number(entry.averageResolutionHours?.toFixed?.(2) ?? entry.averageResolutionHours ?? 0),
                        entry.resolvedTickets ?? 0,
                        entry.closedTickets ?? 0,
                    ])
                    : [["N/A", "N/A", 0, 0, 0]]),
            ];

            const satisfactionRows: (string | number)[][] = [
                ...buildMetadataRows("Customer Satisfaction Report", range),
                ["Customer Satisfaction"],
                ["Total Responses", "Overall", "Resolution", "Communication", "Timeliness", "Composite"],
                [
                    satisfaction.totalResponses ?? 0,
                    Number(satisfaction.overallSatisfactionAverage?.toFixed?.(2) ?? 0),
                    Number(satisfaction.resolutionEffectivenessAverage?.toFixed?.(2) ?? 0),
                    Number(satisfaction.communicationSupportAverage?.toFixed?.(2) ?? 0),
                    Number(satisfaction.timelinessAverage?.toFixed?.(2) ?? 0),
                    Number(satisfaction.compositeScore?.toFixed?.(2) ?? 0),
                ],
                [],
                ["Category", "Sub Category", "Responses", "Composite Score"],
                ...(satisfaction.categoryStats?.length
                    ? satisfaction.categoryStats.map((entry) => [
                        entry.categoryName ?? entry.category ?? "N/A",
                        entry.subcategoryName ?? entry.subcategory ?? "N/A",
                        entry.totalResponses ?? 0,
                        Number(entry.compositeScore?.toFixed?.(2) ?? entry.compositeScore ?? 0),
                    ])
                    : [["N/A", "N/A", 0, 0]]),
            ];

            const problemRows: (string | number)[][] = [
                ...buildMetadataRows("Problem Management Report", range),
                ["Problem Management"],
                ["Category", "Sub Category", "Ticket Count", "Breached Tickets"],
                ...(problemManagement.categoryStats?.length
                    ? problemManagement.categoryStats.map((entry) => [
                        entry.categoryName ?? entry.category ?? "N/A",
                        entry.subcategoryName ?? entry.subcategory ?? "N/A",
                        entry.ticketCount ?? 0,
                        entry.breachedTickets ?? 0,
                    ])
                    : [["N/A", "N/A", 0, 0]]),
            ];

            const sheetDefinitions = [
                { name: "Ticket Summary", rows: summaryRows },
                { name: "Resolution Time", rows: resolutionRows },
                { name: "Customer Satisfaction", rows: satisfactionRows },
                { name: "Problem Management", rows: problemRows },
            ];

            sheetDefinitions.forEach(({ name, rows }) => {
                const worksheet = XLSX.utils.aoa_to_sheet(rows);
                worksheet["!cols"] = calculateColumnWidths(rows);
                applyThinBorders(worksheet);
                XLSX.utils.book_append_sheet(workbook, worksheet, name);
            });

            const fileName = `mis-reports-${period}-${requestParams.toDate || formatDateInput(range.endDate)}.xlsx`;
            XLSX.writeFile(workbook, fileName);
            showMessage("MIS reports downloaded successfully.", "success");
        } catch (error) {
            console.error("Failed to download MIS reports", error);
            const message = error instanceof Error ? error.message : "Failed to download MIS reports.";
            showMessage(message, "error");
        } finally {
            setDownloading(false);
        }
    }, [buildMetadataRows, loadReports, requestParams.toDate, showMessage]);

    const downloadPdf = React.useCallback(async (period: ReportPeriod, range: ReportRange) => {
        setDownloading(true);
        try {
            const { ticketSummary, resolutionTime, satisfaction, problemManagement } = await loadReports();
            const doc = new jsPDF();

            (doc as any).setFontSize?.(14);
            (doc as any).text?.("MIS Reports", 14, 14);
            (doc as any).setFontSize?.(10);
            (doc as any).text?.(`Period: ${getPeriodLabel(period)}`, 14, 20);
            (doc as any).text?.(`From: ${requestParams.fromDate || formatDateInput(range.startDate)}  To: ${requestParams.toDate || formatDateInput(range.endDate)}`, 14, 26);

            autoTable(doc, {
                startY: 32,
                head: [["Ticket Summary", "Value"]],
                body: [
                    ["Total Tickets", String(ticketSummary.totalTickets ?? 0)],
                    ["Open Tickets", String(ticketSummary.openTickets ?? 0)],
                    ["Closed Tickets", String(ticketSummary.closedTickets ?? 0)],
                    ["Avg Resolution Hours", String(Number(resolutionTime.averageResolutionHours?.toFixed?.(2) ?? 0))],
                    ["Tickets Considered", String(resolutionTime.resolvedTicketCount ?? 0)],
                    ["Total Responses", String(satisfaction.totalResponses ?? 0)],
                    ["Composite Score", String(Number(satisfaction.compositeScore?.toFixed?.(2) ?? 0))],
                ],
            });

            autoTable(doc, {
                startY: (((doc as any).lastAutoTable?.finalY) ?? 40) + 8,
                head: [["Problem Management", "Ticket Count"]],
                body: (problemManagement.categoryStats?.length
                    ? problemManagement.categoryStats.slice(0, 20).map((row) => [
                        `${row.categoryName ?? row.category ?? "N/A"} > ${row.subcategoryName ?? row.subcategory ?? "N/A"}`,
                        String(row.ticketCount ?? 0),
                    ])
                    : [["N/A", "0"]]),
            });

            (doc as any).save?.(`mis-reports-${period}-${requestParams.toDate || formatDateInput(range.endDate)}.pdf`);
            showMessage("MIS reports downloaded successfully.", "success");
        } catch (error) {
            console.error("Failed to download MIS reports", error);
            const message = error instanceof Error ? error.message : "Failed to download MIS reports.";
            showMessage(message, "error");
        } finally {
            setDownloading(false);
        }
    }, [loadReports, requestParams.fromDate, requestParams.toDate, showMessage]);

    const handleDownload = async (option: string, period: ReportPeriod, range: ReportRange) => {
        if (option === "excel") {
            await downloadExcel(period, range);
            return;
        }

        if (option === "pdf") {
            await downloadPdf(period, range);
            return;
        }

        showMessage(`${option.toUpperCase()} downloads are not available yet.`, "info");
    };

    const handleEmail = (period: ReportPeriod, range: ReportRange) => {
        const formattedRange = `${range.startDate.toLocaleDateString()} - ${range.endDate.toLocaleDateString()}`;
        showMessage(`${getPeriodLabel(period)} report for ${formattedRange} will be emailed once ready.`, "success");
    };

    return { downloading, handleDownload, handleEmail };
};
