import React from "react";
import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { useSnackbar } from "../context/SnackbarContext";
import { getCurrentUserDetails } from "../config/config";
import { extractApiPayload, formatDateInput } from "../utils/misReports";
import { fetchSlaPerformanceReport } from "../services/ReportService";
import { MISReportRequestParams, SlaPerformanceReportProps } from "../types/reports";
import { ReportPeriod, ReportRange, getPeriodLabel } from "../utils/reportPeriods";

export interface UseSlaReportDownloaderResult {
    downloading: boolean;
    handleDownload: (option: string, period: ReportPeriod, range: ReportRange) => Promise<void>;
    handleEmail: (period: ReportPeriod, range: ReportRange) => void;
}

const formatDuration = (minutes: number | undefined | null) => {
    if (!minutes || Number.isNaN(minutes) || minutes <= 0) {
        return "-";
    }

    const total = Math.floor(minutes);
    if (total < 60) {
        return `${total} mins`;
    }

    const hours = Math.floor(total / 60);
    const remaining = total % 60;
    return remaining === 0 ? `${hours} hrs` : `${hours}h ${remaining}m`;
};

const toFilterSummaryRows = (requestParams: MISReportRequestParams) => {
    const labelMap: Record<string, string> = {
        fromDate: "From Date",
        toDate: "To Date",
        categoryId: "Module",
        subCategoryId: "Sub Module",
        zoneCode: "Zone",
        regionCode: "Region",
        districtCode: "District",
        issueTypeId: "Issue Type",
        division: "Division",
        assignedTo: "Assigned To",
        breachedFilter: "Breached",
    };

    return Object.entries(requestParams)
        .filter(([, value]) => value !== undefined && value !== null && value !== "")
        .map(([key, value]) => [labelMap[key] ?? key, String(value)] as (string | number)[]);
};

export const useSlaReportDownloader = (
    requestParams: MISReportRequestParams,
): UseSlaReportDownloaderResult => {
    const { showMessage } = useSnackbar();
    const userDetails = React.useMemo(() => getCurrentUserDetails(), []);
    const [downloading, setDownloading] = React.useState(false);

    const loadReport = React.useCallback(async () => {
        const response = await fetchSlaPerformanceReport(requestParams);
        const report = extractApiPayload<SlaPerformanceReportProps>(response);
        if (!report) {
            throw new Error("Incomplete data received for SLA report.");
        }
        return report;
    }, [requestParams]);

    const buildMetadataRows = React.useCallback((title: string, period: ReportPeriod, range: ReportRange) => {
        const downloadedBy = userDetails?.username || userDetails?.userId || "Unknown User";
        const downloadedOn = new Date();
        const fromDateLabel = requestParams.fromDate || formatDateInput(range.startDate);
        const toDateLabel = requestParams.toDate || formatDateInput(range.endDate);

        return [
            [title],
            ["Report Generated By", downloadedBy],
            ["Generated On", downloadedOn.toLocaleString()],
            ["Period", getPeriodLabel(period)],
            ["Date Range From", fromDateLabel],
            ["Date Range To", toDateLabel],
            ["Applied Filters", ""],
            ...toFilterSummaryRows(requestParams),
            [],
        ];
    }, [requestParams, userDetails?.userId, userDetails?.username]);

    const downloadExcel = React.useCallback(async (period: ReportPeriod, range: ReportRange) => {
        setDownloading(true);

        try {
            const report = await loadReport();
            const workbook = XLSX.utils.book_new();

            const totalBreached = (report.totalBreachedTickets ?? 0);
            const totalNotBreached = (report.totalOnTrackTickets ?? 0) + (report.totalResolvedWithinSla ?? 0);

            const summaryRows: (string | number)[][] = [
                ...buildMetadataRows("SLA Performance Report", period, range),
                ["SLA Summary"],
                ["Total Tickets", "Breached", "Not Breached", "Breach Rate %", "Avg Breach"],
                [
                    report.totalTicketsWithSla ?? 0,
                    totalBreached,
                    totalNotBreached,
                    Number(report.breachRate?.toFixed?.(2) ?? report.breachRate ?? 0),
                    formatDuration(report.averageBreachMinutes),
                ],
                [],
                ["Ticket State", "Count"],
                ["Breached - Resolved", report.breachedResolvedTickets ?? 0],
                ["Breached - Closed", report.breachedClosedTickets ?? 0],
                ["Breached - In Progress", report.breachedInProgressTickets ?? 0],
                ["Not Breached - Resolved", report.notBreachedResolvedTickets ?? 0],
                ["Not Breached - Closed", report.notBreachedClosedTickets ?? 0],
                ["Not Breached - In Progress", report.notBreachedInProgressTickets ?? 0],
            ];

            const severityRows: (string | number)[][] = [
                ...buildMetadataRows("SLA by Severity", period, range),
                ["Severity", "Total", "Breached", "On Track", "Resolved Within SLA", "Resolved After Breach"],
                ...(report.severityBreakdown?.length
                    ? report.severityBreakdown.map((item) => [
                        item.severity ?? "N/A",
                        item.total ?? 0,
                        item.breached ?? 0,
                        item.onTrack ?? 0,
                        item.resolvedWithinSla ?? 0,
                        item.resolvedAfterBreach ?? 0,
                    ])
                    : [["N/A", 0, 0, 0, 0, 0]]),
            ];

            const breachedInProgressRows: (string | number)[][] = [
                ...buildMetadataRows("Breached Tickets In Progress", period, range),
                ["Ticket Number", "Subject", "Assignee", "Severity", "Status", "Due At", "Breached By"],
                ...(report.breachedTickets?.filter((ticket) => (ticket.status ?? "").toLowerCase().includes("progress")).length
                    ? report.breachedTickets
                        .filter((ticket) => (ticket.status ?? "").toLowerCase().includes("progress"))
                        .map((ticket) => [
                            ticket.ticketNumber ?? "-",
                            ticket.subject ?? "-",
                            ticket.assignee ?? "-",
                            ticket.severity ?? "-",
                            ticket.status ?? "-",
                            ticket.dueAt ? new Date(ticket.dueAt).toLocaleString() : "-",
                            formatDuration(ticket.breachedByMinutes ?? 0),
                        ])
                    : [["-", "No breached in-progress tickets", "-", "-", "-", "-", "-"]]),
            ];

            const makeSheet = (name: string, rows: (string | number)[][]) => {
                const worksheet = XLSX.utils.aoa_to_sheet(rows);
                XLSX.utils.book_append_sheet(workbook, worksheet, name);
            };

            makeSheet("SLA Summary", summaryRows);
            makeSheet("SLA By Severity", severityRows);
            makeSheet("Breached In Progress", breachedInProgressRows);

            XLSX.writeFile(workbook, `sla-reports-${period}-${requestParams.toDate || formatDateInput(range.endDate)}.xlsx`);
            showMessage("SLA report downloaded successfully.", "success");
        } catch (error) {
            console.error("Failed to download SLA report", error);
            const message = error instanceof Error ? error.message : "Failed to download SLA report.";
            showMessage(message, "error");
        } finally {
            setDownloading(false);
        }
    }, [buildMetadataRows, loadReport, requestParams.toDate, showMessage]);

    const downloadPdf = React.useCallback(async (period: ReportPeriod, range: ReportRange) => {
        setDownloading(true);

        try {
            const report = await loadReport();
            const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });

            const fromDate = requestParams.fromDate || formatDateInput(range.startDate);
            const toDate = requestParams.toDate || formatDateInput(range.endDate);
            const filters = toFilterSummaryRows(requestParams);

            doc.setFontSize(14);
            doc.text("SLA Performance Report", 40, 40);
            doc.setFontSize(10);
            doc.text(`Period: ${getPeriodLabel(period)}`, 40, 58);
            doc.text(`From: ${fromDate}   To: ${toDate}`, 40, 72);

            autoTable(doc, {
                startY: 84,
                head: [["SLA KPI", "Value"]],
                body: [
                    ["Total Tickets", String(report.totalTicketsWithSla ?? 0)],
                    ["Total Breached", String(report.totalBreachedTickets ?? 0)],
                    ["Total Not Breached", String((report.totalOnTrackTickets ?? 0) + (report.totalResolvedWithinSla ?? 0))],
                    ["Breached - Resolved", String(report.breachedResolvedTickets ?? 0)],
                    ["Breached - Closed", String(report.breachedClosedTickets ?? 0)],
                    ["Breached - In Progress", String(report.breachedInProgressTickets ?? 0)],
                    ["Not Breached - Resolved", String(report.notBreachedResolvedTickets ?? 0)],
                    ["Not Breached - Closed", String(report.notBreachedClosedTickets ?? 0)],
                    ["Not Breached - In Progress", String(report.notBreachedInProgressTickets ?? 0)],
                    ["Breach Rate", `${Number(report.breachRate?.toFixed?.(2) ?? report.breachRate ?? 0)}%`],
                    ["Average Breach", formatDuration(report.averageBreachMinutes)],
                ],
            });

            autoTable(doc, {
                startY: ((doc as any).lastAutoTable?.finalY ?? 100) + 10,
                head: [["Applied Filter", "Value"]],
                body: filters.length ? filters as string[][] : [["None", "All Data"]],
            });

            autoTable(doc, {
                startY: ((doc as any).lastAutoTable?.finalY ?? 140) + 10,
                head: [["Severity", "Total", "Breached", "On Track", "Resolved Within SLA", "Resolved After Breach"]],
                body: report.severityBreakdown?.length
                    ? report.severityBreakdown.map((item) => [
                        item.severity ?? "N/A",
                        String(item.total ?? 0),
                        String(item.breached ?? 0),
                        String(item.onTrack ?? 0),
                        String(item.resolvedWithinSla ?? 0),
                        String(item.resolvedAfterBreach ?? 0),
                    ])
                    : [["N/A", "0", "0", "0", "0", "0"]],
            });

            const breachedInProgress = report.breachedTickets?.filter(
                (ticket) => (ticket.status ?? "").toLowerCase().includes("progress"),
            ) ?? [];

            autoTable(doc, {
                startY: ((doc as any).lastAutoTable?.finalY ?? 220) + 10,
                head: [["Ticket", "Subject", "Assignee", "Severity", "Status", "Due At", "Breached By"]],
                body: breachedInProgress.length
                    ? breachedInProgress.map((ticket) => [
                        ticket.ticketNumber ?? "-",
                        ticket.subject ?? "-",
                        ticket.assignee ?? "-",
                        ticket.severity ?? "-",
                        ticket.status ?? "-",
                        ticket.dueAt ? new Date(ticket.dueAt).toLocaleString() : "-",
                        formatDuration(ticket.breachedByMinutes ?? 0),
                    ])
                    : [["-", "No breached in-progress tickets", "-", "-", "-", "-", "-"]],
                styles: { fontSize: 8 },
                headStyles: { fontSize: 9 },
            });

            doc.save(`sla-reports-${period}-${requestParams.toDate || formatDateInput(range.endDate)}.pdf`);
            showMessage("SLA report downloaded successfully.", "success");
        } catch (error) {
            console.error("Failed to download SLA report", error);
            const message = error instanceof Error ? error.message : "Failed to download SLA report.";
            showMessage(message, "error");
        } finally {
            setDownloading(false);
        }
    }, [loadReport, requestParams, showMessage]);

    const handleDownload = async (option: string, period: ReportPeriod, range: ReportRange) => {
        if (option === "excel") {
            await downloadExcel(period, range);
            return;
        }

        if (option === "pdf") {
            await downloadPdf(period, range);
            return;
        }

        showMessage(`${option.toUpperCase()} downloads are not available yet.`, "info");
    };

    const handleEmail = (period: ReportPeriod, range: ReportRange) => {
        const formattedRange = `${range.startDate.toLocaleDateString()} - ${range.endDate.toLocaleDateString()}`;
        showMessage(`${getPeriodLabel(period)} SLA report for ${formattedRange} will be emailed once ready.`, "success");
    };

    return { downloading, handleDownload, handleEmail };
};
