FROM php:8.3

RUN apt-get update > /dev/null
RUN apt-get install -y --no-install-recommends nodejs npm libldap2-dev libzip-dev ca-certificates && rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
RUN docker-php-ext-install zip ldap
RUN docker-php-ext-enable zip ldap
RUN docker-php-ext-install mysqli

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR "/var/www/filegator/"

COPY . .
COPY ./backend/php.ini /usr/local/etc/php/php.ini
RUN composer install
ENV CYPRESS_INSTALL_BINARY=0

RUN npm i
# RUN cp -n configuration_sample.php configuration.php

CMD ["nohup", "bash", "-c", "npm run serve"]
