apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filegator-repository-pvc
  labels:
    app: filegator
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
