package com.ticketingSystem.api.common;
// Generated 3 Aug, 2015 5:16:33 PM by Hibernate Tools 4.3.1


import com.ticketingSystem.api.enums.RepositoryType;
import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Repositorydefinition generated by hbm2java
 */
@Entity
@Table(name="repositorydefinition"
)
public class Repositorydefinition implements java.io.Serializable {
     private int id;
     private String repositoryname;
     private RepositoryType repositorytype;
     private String repositoryroot;
     private Set<Documentinfo> documentinfo = new HashSet<Documentinfo>(0);

    public Repositorydefinition() {
    }

	
    public Repositorydefinition(int id) {
        this.id = id;
    }
    public Repositorydefinition(int id, String repositoryname, com.ticketingSystem.api.enums.RepositoryType repositorytype, String repositoryroot, Set<Documentinfo> documentinfo) {
       this.id = id;
       this.repositoryname = repositoryname;
       this.repositorytype = repositorytype;
       this.repositoryroot = repositoryroot;
       this.documentinfo = documentinfo;
    }
   
    @Id 
 	@Column(name="id", unique=true, nullable=false)
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="repositoryname")
    public String getRepositoryname() {
        return this.repositoryname;
    }
    
    public void setRepositoryname(String repositoryname) {
        this.repositoryname = repositoryname;
    }

    
    @Column(name="repositorytype", columnDefinition = "smallint")
	//@NoConvert(converter = EnumConverter.class)
    public RepositoryType getRepositorytype() {
        return this.repositorytype;
    }
    
    public void setRepositorytype(RepositoryType repositorytype) {
        this.repositorytype = repositorytype;
    }

    
    @Column(name="repositoryroot")
    public String getRepositoryroot() {
        return this.repositoryroot;
    }
    
    public void setRepositoryroot(String repositoryroot) {
        this.repositoryroot = repositoryroot;
    }

   @OneToMany(fetch=FetchType.LAZY, mappedBy="repositorydefinition", cascade = {CascadeType.ALL})
    public Set<Documentinfo> getDocumentinfo() {
        return this.documentinfo;
    }
    
    public void setDocumentinfo(Set<Documentinfo> documentinfo) {
        this.documentinfo = documentinfo;
    }
}


