import React, { useEffect, useMemo, useState } from "react";
import { Box, TextField, Typography } from "@mui/material";
import Title from "../Title";
import { MISReportRequestParams } from "../../types/reports";
import { getCurrentUserDetails } from "../../config/config";

const ADMIN_ROLES = new Set(["Team Lead", "System Administrator", "Regional Nodal Officer"]);

const formatDateInput = (date: Date) => date.toISOString().split("T")[0];

interface ReportPageLayoutProps {
    title: string;
    children: (params: MISReportRequestParams) => React.ReactNode;
    description?: React.ReactNode;
}

const ReportPageLayout: React.FC<ReportPageLayoutProps> = ({ title, children, description }) => {
    const [dateRange, setDateRange] = useState<{ from: string; to: string }>(() => {
        const today = new Date();
        const start = new Date();
        start.setDate(today.getDate() - 30);
        return { from: formatDateInput(start), to: formatDateInput(today) };
    });
    const [generatedOn, setGeneratedOn] = useState<Date>(() => new Date());

    const userDetails = useMemo(() => getCurrentUserDetails(), []);
    const viewScope: MISReportRequestParams["scope"] = useMemo(() => {
        const roles = userDetails?.role ?? [];
        return roles.some((role) => ADMIN_ROLES.has(role)) ? "all" : "user";
    }, [userDetails?.role]);

    const requestParams = useMemo<MISReportRequestParams>(() => {
        return {
            fromDate: dateRange.from,
            toDate: dateRange.to,
            scope: viewScope,
            userId: userDetails?.userId,
        };
    }, [dateRange.from, dateRange.to, userDetails?.userId, viewScope]);

    useEffect(() => {
        setGeneratedOn(new Date());
    }, [dateRange.from, dateRange.to, viewScope]);

    const handleDateChange = (key: "from" | "to") => (event: React.ChangeEvent<HTMLInputElement>) => {
        const value = event.target.value;

        setDateRange((previous) => {
            if (key === "from" && previous.to && value && value > previous.to) {
                return { from: value, to: value };
            }

            if (key === "to" && previous.from && value && value < previous.from) {
                return { from: value, to: value };
            }

            return { ...previous, [key]: value };
        });
    };

    const formatDisplayDate = (value: string | Date) =>
        new Date(value).toLocaleDateString(undefined, {
            year: "numeric",
            month: "short",
            day: "numeric",
        });

    const generatedBy = userDetails?.username || userDetails?.userId || "Unknown User";

    return (
        <Box display="flex" flexDirection="column" gap={3} p={2}>
            <Title textKey={title} />

            {description && (
                <Typography variant="body2" color="text.secondary">
                    {description}
                </Typography>
            )}

            <Box display="flex" gap={3} flexWrap="wrap" alignItems="center">
                <Typography variant="body2" color="text.secondary">
                    Generated By: <strong>{generatedBy}</strong>
                </Typography>
                <Typography variant="body2" color="text.secondary">
                    From: <strong>{formatDisplayDate(requestParams.fromDate || dateRange.from)}</strong>
                </Typography>
                <Typography variant="body2" color="text.secondary">
                    To: <strong>{formatDisplayDate(requestParams.toDate || dateRange.to)}</strong>
                </Typography>
                <Typography variant="body2" color="text.secondary">
                    Generated On: <strong>{formatDisplayDate(generatedOn)}</strong>
                </Typography>
                <Typography variant="body2" color="text.secondary">
                    Viewing: <strong>{viewScope === "all" ? "All Tickets" : "My Workload"}</strong>
                </Typography>
            </Box>

            <Box display="flex" gap={2} flexWrap="wrap">
                <TextField
                    id="mis-report-from"
                    label="From Date"
                    type="date"
                    value={dateRange.from}
                    onChange={handleDateChange("from")}
                    InputLabelProps={{ shrink: true }}
                    size="small"
                />
                <TextField
                    id="mis-report-to"
                    label="To Date"
                    type="date"
                    value={dateRange.to}
                    onChange={handleDateChange("to")}
                    InputLabelProps={{ shrink: true }}
                    size="small"
                />
            </Box>

            {children(requestParams)}
        </Box>
    );
};

export default ReportPageLayout;
