ALTER TABLE tickets
    ADD COLUMN IF NOT EXISTS office VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS office_code VARCHAR(100) NULL,
    ADD COLUMN IF NOT EXISTS district_code VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS zone_code VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(50) NULL,
    ADD COLUMN IF NOT EXISTS region_name VARCHAR(255) NULL,
    ADD COLUMN IF NOT EXISTS district_name VARCHAR(255) NULL;
