INSERT INTO page_master (
    page_name,
    page_code,
    page_description,
    parent_id,
    is_active,
    is_on_sidebar,
    created_on,
    created_by,
    updated_on,
    updated_by
) VALUES
    ('Support Dashboard', 'supportDashboard', 'Support Dashboard', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('All Tickets', 'allTickets', 'All Tickets', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('My Tickets', 'myTickets', 'My Tickets', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('My Workload', 'myWorkload', 'My Workload', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Calendar', 'calendar', 'Calendar', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Root Cause Analysis', 'rootCauseAnalysis', 'Root Cause Analysis', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Raise Ticket', 'raiseTicket', 'Raise Ticket', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('FAQ', 'faq', 'FAQ', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Knowledge Base', 'knowledgeBase', 'Knowledge Base', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('SLA Reports', 'slaReports', 'SLA Reports', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('MIS Reports', 'misReports', 'MIS Reports', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Modules Master', 'modulesMaster', 'Modules Master', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Escalation Master', 'escalationMaster', 'Escalation Master', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Role Master', 'roleMaster', 'Role Master', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Users', 'users', 'Users', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('My Profile', 'myProfile', 'My Profile', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Add New User', 'addNewUser', 'Add New User', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system'),
    ('Dashboard', 'dashboard', 'Dashboard', NULL, TRUE, TRUE, NOW(), 'system', NOW(), 'system');
