version: '3.3'

services:
  typesense:
    image: typesense/typesense:0.25.1 
    container_name: typesense
    ports:
      - "8108:8108"
    volumes:
      - ./data:/data
    command: >
      typesense-server --data-dir /data --api-key=xyz123 --enable-cors
